site_name: FlyingDutchman

nav:
  - Home: index.md
  - My First Page: my-first-page.md

theme: material

plugins:
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true

markdown_extensions:
  - admonition  # adds callout blocks like !!! note, !!! tip, !!! warning
  - pymdownx.details # allows collapsible sections using ??? "Click to expand"
  - pymdownx.superfences  # enables nested or advanced fenced code blocks (for tabs)
  - pymdownx.tabbed:  # enables content tabs with === "Tab" syntax
      alternate_style: true  # optional style variation for tabs
  - pymdownx.tasklist:  # renders checkboxes for - [ ] and - [x] lists
      custom_checkbox: true  # use themed checkboxes instead of plain bullets
